version: '2'

services:
  icecast:
    image: vitiman/alpine-icecast:latest
    ports:
      - "8000:8000"
    networks:
      - music_stack

  liquidsoap:
    build:
      context: liquidsoap/
    image: liquidsoap:latest
    networks:
      - music_stack

networks:
  music_stack:
    driver: bridge

# If you use your own volumes instead host volumes, uncomment this section
# volumes:
#   mpd_music:
#     external: true
#   mpd_playlists:
#     external: true
#   mpd_database:
#     external: true


